# Generated by Django 3.1.7 on 2021-05-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210504_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, max_length=10000, upload_to=''),
        ),
    ]
