# Generated by Django 3.1.7 on 2021-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_producthost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productdesc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producthost',
            new_name='product_host',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producter',
        ),
        migrations.AddField(
            model_name='product',
            name='exclude_api',
            field=models.CharField(max_length=2000, null=True, verbose_name='排除接口'),
        ),
    ]
