# Generated by Django 3.1.7 on 2021-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210531_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exclude_api',
            field=models.CharField(default='', max_length=2000, verbose_name='排除接口'),
        ),
    ]
