# Generated by Django 3.1.7 on 2021-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名称')),
                ('setvalue', models.CharField(max_length=200, verbose_name='xxx')),
            ],
            options={
                'verbose_name': '用户名称',
                'verbose_name_plural': '用户名称',
            },
        ),
    ]
