# Generated by Django 3.1.7 on 2021-03-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
