# Generated by Django 3.1.7 on 2021-05-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_producthost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFlowTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_name', models.CharField(max_length=64, verbose_name='流程接口名称')),
                ('api_test_desc', models.CharField(max_length=64, verbose_name='描述')),
                ('api_tester', models.CharField(max_length=16, verbose_name='测试负责人')),
                ('api_test_result', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '流程场景接口',
                'verbose_name_plural': '流程场景接口',
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(max_length=100, verbose_name='变量名')),
                ('variable_value', models.CharField(max_length=1000, null=True, verbose_name='变量值')),
                ('from_api', models.CharField(max_length=1000, null=True, verbose_name='所属接口')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '参数',
                'verbose_name_plural': '参数',
            },
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_key', models.CharField(max_length=100, verbose_name='变量名')),
                ('header_value', models.CharField(max_length=1000, verbose_name='变量值')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'header',
                'verbose_name_plural': 'header',
            },
        ),
        migrations.CreateModel(
            name='ApiStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('api_url', models.CharField(max_length=200, verbose_name='url 地址')),
                ('api_step', models.CharField(max_length=100, null=True, verbose_name='测试步骤')),
                ('api_param_value', models.CharField(max_length=800, verbose_name='请求参数和值')),
                ('api_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法')),
                ('api_result', models.CharField(max_length=200, null=True, verbose_name='预期结果')),
                ('api_response', models.CharField(max_length=5000, null=True, verbose_name='响应数据')),
                ('api_status', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('ApiFlowTest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.apiflowtest')),
            ],
        ),
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('api_url', models.CharField(max_length=200, verbose_name='url 地址')),
                ('api_param_value', models.CharField(max_length=500, null=True, verbose_name='请求参数')),
                ('api_body_value', models.CharField(max_length=1000, null=True, verbose_name='请求body')),
                ('api_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='0', max_length=200, verbose_name='请求方法')),
                ('api_expect_response', models.CharField(max_length=500, null=True, verbose_name='预期结果')),
                ('api_expect_status_code', models.IntegerField(default=200, verbose_name='预期状态码')),
                ('api_response', models.CharField(max_length=1000, null=True, verbose_name='测试结果')),
                ('api_response_status_code', models.IntegerField(null=True, verbose_name='预期状态码')),
                ('api_status', models.BooleanField(null=True, verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('test', models.CharField(max_length=100, null=True, verbose_name='test')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '单一场景接口',
                'verbose_name_plural': '单一场景接口',
            },
        ),
    ]
