# Generated by Django 3.1.7 on 2021-03-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apimethod',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='0', max_length=200, verbose_name='请求方法'),
        ),
    ]
