# Generated by Django 3.1.7 on 2021-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20210314_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='apibodyvalue',
            field=models.CharField(max_length=1000, null=True, verbose_name='请求body'),
        ),
        migrations.AddField(
            model_name='apis',
            name='apiexpectstatus',
            field=models.IntegerField(default=200, verbose_name='预期状态码'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='apiparamvalue',
            field=models.CharField(max_length=500, null=True, verbose_name='请求参数'),
        ),
    ]
