# Generated by Django 3.1.7 on 2021-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20210521_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiflowandapis',
            name='execution_order',
            field=models.IntegerField(null=True, verbose_name='执行顺序'),
        ),
    ]
