# Generated by Django 3.1.7 on 2021-04-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210313_2005'),
        ('apitest', '0003_auto_20210411_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(max_length=100, verbose_name='变量名')),
                ('variable_value', models.CharField(max_length=1000, verbose_name='变量值')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '参数',
                'verbose_name_plural': '参数',
            },
        ),
    ]
