# Generated by Django 3.1.7 on 2021-05-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20210521_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apis',
            name='test',
        ),
    ]
