# Generated by Django 3.1.7 on 2021-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='from_api',
            field=models.CharField(max_length=1000, null=True, verbose_name='所属接口'),
        ),
    ]
