# Generated by Django 3.1.7 on 2021-05-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_remove_apis_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiflowandapis',
            old_name='param_to_use',
            new_name='input_parameter',
        ),
        migrations.RenameField(
            model_name='apiflowandapis',
            old_name='param_to_save',
            new_name='output_parameter',
        ),
    ]
