# Generated by Django 3.1.7 on 2021-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_variables_from_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='variable_value',
            field=models.CharField(max_length=1000, null=True, verbose_name='变量值'),
        ),
    ]
