# Generated by Django 3.1.7 on 2021-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20210406_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apiresult',
            field=models.CharField(default='None', max_length=200, null=True, verbose_name='预期结果'),
        ),
    ]
