# Generated by Django 3.1.7 on 2021-05-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20210524_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiflowtest',
            old_name='api_test_desc',
            new_name='case_desc',
        ),
        migrations.RenameField(
            model_name='apiflowtest',
            old_name='api_test_name',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='apiflowtest',
            old_name='api_test_result',
            new_name='case_test_result',
        ),
        migrations.RenameField(
            model_name='apiflowtest',
            old_name='api_tester',
            new_name='case_tester',
        ),
    ]
