# Generated by Django 3.1.7 on 2021-05-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20210520_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apistep',
            old_name='Apitest',
            new_name='ApiFlowTest',
        ),
    ]
