# Generated by Django 3.1.7 on 2021-04-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20210406_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
    ]
