# Generated by Django 3.1.7 on 2021-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20210524_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiflowtest',
            name='case_test_result',
            field=models.BooleanField(null=True, verbose_name='测试结果'),
        ),
    ]
