# Generated by Django 3.1.7 on 2021-05-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_producthost'),
        ('apitest', '0008_auto_20210520_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apitest',
            new_name='ApiFlowTest',
        ),
    ]
