# Generated by Django 3.1.7 on 2021-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20210406_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apis',
            old_name='apiexpectstatus',
            new_name='apiexpectstatuscode',
        ),
        migrations.RemoveField(
            model_name='apis',
            name='apiresult',
        ),
        migrations.AddField(
            model_name='apis',
            name='apiexpectresponse',
            field=models.CharField(max_length=500, null=True, verbose_name='预期结果'),
        ),
        migrations.AddField(
            model_name='apis',
            name='apiresponse',
            field=models.CharField(max_length=500, null=True, verbose_name='测试结果'),
        ),
        migrations.AddField(
            model_name='apis',
            name='apiresponsestatuscode',
            field=models.IntegerField(null=True, verbose_name='预期状态码'),
        ),
    ]
