# Generated by Django 3.1.7 on 2021-05-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20210520_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apistep',
            old_name='ApiFlowTest',
            new_name='ApiTest',
        ),
    ]
