# Generated by Django 3.1.7 on 2021-05-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20210524_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiflowtest',
            old_name='case_test_result',
            new_name='test_result',
        ),
        migrations.RenameField(
            model_name='apis',
            old_name='api_status',
            new_name='test_result',
        ),
    ]
