# Generated by Django 3.1.7 on 2021-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0010_auto_20210526_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='api_body_value',
            field=models.CharField(max_length=2000, null=True, verbose_name='请求body'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='api_param_value',
            field=models.CharField(max_length=1000, null=True, verbose_name='请求参数'),
        ),
    ]
