# Generated by Django 3.1.7 on 2021-05-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0011_auto_20210530_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='variable_optional',
            field=models.BooleanField(null=True, verbose_name='是否可选'),
        ),
        migrations.AddField(
            model_name='variables',
            name='variable_type',
            field=models.CharField(max_length=100, null=True, verbose_name='变量类型'),
        ),
    ]
