# Generated by Django 3.1.7 on 2021-07-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0013_apis_not_for_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='variable_value',
            field=models.CharField(max_length=10000, null=True, verbose_name='变量值'),
        ),
    ]
