# Generated by Django 3.1.7 on 2021-08-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0015_auto_20210701_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='api_response_last_time',
            field=models.TextField(max_length=50000, null=True, verbose_name='上次返回结果结果'),
        ),
    ]
