# Generated by Django 3.1.7 on 2021-08-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0016_apis_api_response_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='api_expect_response',
            field=models.TextField(max_length=50000, null=True, verbose_name='预期结果'),
        ),
    ]
