# Generated by Django 3.1.7 on 2021-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0017_auto_20210816_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='api_response',
            field=models.TextField(max_length=50000, null=True, verbose_name='测试结果'),
        ),
    ]
