# Generated by Django 3.1.7 on 2021-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0018_auto_20210816_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='variable_depend_api_id',
            field=models.CharField(max_length=200, null=True, verbose_name='依赖接口'),
        ),
        migrations.AddField(
            model_name='variables',
            name='variable_need_preparation',
            field=models.BooleanField(null=True, verbose_name='数据准备'),
        ),
        migrations.AddField(
            model_name='variables',
            name='variable_reach_json_path',
            field=models.CharField(max_length=200, null=True, verbose_name='取参规则'),
        ),
    ]
