# Generated by Django 3.1.7 on 2021-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0019_auto_20210816_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='api_response_status_code',
            field=models.IntegerField(null=True, verbose_name='实际状态码'),
        ),
    ]
