# Generated by Django 3.1.7 on 2021-03-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='buglever',
            new_name='buglevel',
        ),
    ]
